version: "3"
services:
  graphdb:
    build:
      context: .
      args:
        GRAPHDB_ZIP: ${GRAPHDB_ZIP}
    image: graphdb-server
    restart: always
    environment:
      GDB_HEAP_SIZE: ${GDB_HEAP_SIZE}
    ports:
      - "7200:7200"
    volumes:
      - ./import:/root/graphdb-import
